spring.application.name=resena

# Para que los tests levanten el contexto sin MySQL
spring.datasource.url=jdbc:h2:mem:resena_db;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

