server.port=8086

spring.application.name=carrito

spring.datasource.url=jdbc:mysql://localhost:3306/db_carrito
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
